### DISCUSSION TITLE
What are api-ms-* dlls and why are they copied?

### DISCUSSION THREAD

**Discussion by bicobus** [marcelotduarte/cx_Freeze#2171] [Q&A]
I recently did a cxFreeze build using github actions, and found out that cxFreeze will copy those files from the PowerShell folder (`C:\Program Files\PowerShell\7\`).

What are those files?
Are they needed?
Why are they needed? 
If not, how do I prevent their copy?

I did not set the include_msvcr option, at all. Is it related to it? Sorry if those questions seems ridiculous, I simply have no idea what the api-ms-* dlls are about.

**Comment by marcelotduarte** [comment]
They are copied from the first directory in the PATH.
https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c
https://cx-freeze.readthedocs.io/en/stable/faq.html#microsoft-visual-c-redistributable-package

**Reply by bicobus** [reply]
Reading the cx_Freeze doc:

> If your license allows you to distribute these files, specify the `include_msvcr` option to [build_exe](https://cx-freeze.readthedocs.io/en/stable/setup_script.html#cx-freeze-build-exe) to have them distributed automatically.

I did not specify that option, assuming it would be `False` by default. Am I assuming wrong?

For context, this is the [build](https://github.com/BannerlordCE/pyCEStoriesEditor/actions/runs/7237843779/job/19717980173).

Extent of build_exe:
```toml
[tool.distutils.build_exe]
excludes = [
  "tkinter", "gi", "gtk", "PyQt4", "PyQt5", "PyQt6",
  "PySide2", "PySide6", "shiboken2", "shiboken6", "lib2to3"
]
packages = ["xsdata_attrs.hooks"]
```
