### ISSUE TITLE
Add support for pyproject.toml

### ISSUE THREAD

**Issue by JakobDev** [marcelotduarte/cx_Freeze#1569]
It would be nice if cx_Freeze could support pyproject.toml. Something like this:
``` toml
# All Platforms
[tool.cx_Freeze]
packages = ["os"]
excludes = ["tkinter"]
script = "my_cool_program.py"

# Additional settings for a specific platform
[tool.cx_Freeze.Platform.Windows]
base = "Win32GUI"
icon = "my_icon.ico"
``` 
This could be build by running `python -m cx_Freeze build` in the directory of the pyproject.toml.
