### ISSUE TITLE
error while loading shared libraries: libcrypt-06cd74a6.so.2 on aarch64

### ISSUE THREAD

**Issue by qstokkink** [marcelotduarte/cx_Freeze#2641]
_[EDIT]_ **tl;dr "official" workaround** ([posted below](https://github.com/marcelotduarte/cx_Freeze/issues/2641#issuecomment-2439728292)):

> Copy the libcrypt library that is distributed with cx_Freeze, it is located in cx_Freeze/bases/lib.

---

I used `Ubuntu 22.04 aarch64` to create a build, which also works on `Ubuntu 22.04 amd64` with the same setup. However, when running a build produced on `Ubuntu 22.04 aarch64` specifically I get the following error.

```
error while loading shared libraries: libcrypt-06cd74a6.so.2: cannot open shared object file: No such file or directory
```

 - Platform information: Ubuntu 22.04
 - OS architecture: aarch64
 - cx_Freeze version: 7.2.3 (`cx_Freeze-7.2.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl` from pip)
 - Python version: 3.10

**My solution**
To solve this, I had to do two things. First, copy `libcrypt.so.1` into the local directory as `libcrypt-06cd74a6.so.2`:

```
cp /lib/aarch64-linux-gnu/libcrypt.so.1 libcrypt-06cd74a6.so.2
```

Second, I added the following to the `build_exe` `include_files` entry:

```python
("libcrypt-06cd74a6.so.2", "lib/libcrypt-06cd74a6.so.2")
```

For now my solution works. However, I guess my approach is very fragile and I think it would be better if this got solved on your side.

**Comment by marcelotduarte** [comment]
I thought #2624 fixed this issue, but I cannot test it on ARM.
You can get the wheel to test from the [build](https://github.com/marcelotduarte/cx_Freeze/actions/runs/11493799016/artifacts/2097435733).

**Comment by qstokkink** [comment]
I just tested the wheel you linked (`cx_Freeze-7.3.0.dev0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`) and I get `error while loading shared libraries: libcrypt-06cd74a6.so.2: cannot open shared object file: No such file or directory` again.

By the way, for reproduction, the way I test using GitHub Actions is roughly this (but actually [here](https://github.com/qstokkink/tribler/blob/ad28d0898f22dbb45c5665b0e939723db84ecb28/.github/workflows/build_cross_deb.yml)):

```yml
name: Build Cross Deb
on: workflow_dispatch

jobs:
  aarch64_job:
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-tags: 'true'
      - uses: uraimo/run-on-arch-action@v2
        name: Compile aarch64
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/myproject"
          shell: /bin/sh
          install: |
            apt-get update -q -y
            apt-get install -q -y --allow-downgrades python3-pip
          run: |
            cd myproject
            python3 -m pip install --upgrade cx_Freeze-7.3.0.dev0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
            
            # Use cx_Freeze to make a build
            export PATH="/usr/local/bin:$PATH"
            ./mybuildscript.sh

            # Do a test run (Actions eats the output without the || true)
            timeout 10s ./executable || true
```
